version: '3.5'
services:
  postgres:
    image: 'postgres:12.4'
    environment:
      POSTGRES_DB: 'application-style'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432'

  application-style:
    build:
      context: .
    ports:
    - '8080'
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
      SPRING_PROFILES_ACTIVE: 'local'
    links:
      - postgres
